# Generated by Django 5.2.4 on 2026-03-10 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                ("incident_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Info"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("investigating", "Investigating"),
                            ("resolved", "Resolved"),
                            ("escalated", "Escalated"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("malware", "Malware"),
                            ("phishing", "Phishing"),
                            ("brute-force", "Brute Force"),
                            ("data-exfiltration", "Data Exfiltration"),
                            ("insider-threat", "Insider Threat"),
                            ("dos", "DoS"),
                            ("unauthorized-access", "Unauthorized Access"),
                            ("reconnaissance", "Reconnaissance"),
                        ],
                        max_length=50,
                    ),
                ),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("target_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("ai_summary", models.TextField(blank=True, default="")),
                ("confidence_score", models.IntegerField(default=0, help_text="0-100")),
                ("risk_score", models.IntegerField(default=0, help_text="0-100")),
                (
                    "affected_assets",
                    models.JSONField(
                        default=list, help_text="List of affected assets/hostnames"
                    ),
                ),
                ("is_false_positive", models.BooleanField(default=False)),
                (
                    "source",
                    models.CharField(
                        default="manual",
                        help_text="Source of incident: manual, splunk, elasticsearch, api, etc.",
                        max_length=100,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="External incident ID from source system",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="incidents_i_created_c4c91a_idx"
                    ),
                    models.Index(
                        fields=["severity", "-created_at"],
                        name="incidents_i_severit_5e28cd_idx",
                    ),
                    models.Index(
                        fields=["status"], name="incidents_i_status_9a4f12_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                ("alert_id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Info"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw alert JSON from source system",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="incidents.incident",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeBase",
            fields=[
                ("kb_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "tags",
                    models.JSONField(default=list, help_text="Tags for categorization"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_incidents",
                    models.ManyToManyField(
                        blank=True,
                        related_name="knowledge_base",
                        to="incidents.incident",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Knowledge Base",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                ("entity_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("ip", "IP Address"),
                            ("hostname", "Hostname"),
                            ("email", "Email"),
                            ("domain", "Domain"),
                            ("user", "User Account"),
                            ("file_hash", "File Hash"),
                            ("url", "URL"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("context_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "incidents",
                    models.ManyToManyField(
                        blank=True, related_name="entities", to="incidents.incident"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("name", "entity_type")},
            },
        ),
    ]
