# Generated by Django 5.2.4 on 2026-04-06 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("org_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SoarPlaybookExecution",
            fields=[
                ("execution_id", models.AutoField(primary_key=True, serialize=False)),
                ("playbook", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                (
                    "external_execution_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.CreateModel(
            name="ThreatIntelIndicator",
            fields=[
                ("indicator_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "indicator_type",
                    models.CharField(
                        choices=[
                            ("ip", "IP Address"),
                            ("domain", "Domain"),
                            ("url", "URL"),
                            ("file_hash", "File Hash"),
                            ("email", "Email"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.CharField(max_length=500)),
                ("source", models.CharField(default="manual", max_length=120)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Info"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "confidence_score",
                    models.IntegerField(default=50, help_text="0-100"),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("first_seen", models.DateTimeField(blank=True, null=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="incident",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incidents",
                to="incidents.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="incidents_i_organiz_a7031e_idx",
            ),
        ),
        migrations.AddField(
            model_name="soarplaybookexecution",
            name="incident",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="soar_executions",
                to="incidents.incident",
            ),
        ),
        migrations.AddField(
            model_name="soarplaybookexecution",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="soar_executions",
                to="incidents.organization",
            ),
        ),
        migrations.AddField(
            model_name="threatintelindicator",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threat_indicators",
                to="incidents.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="soarplaybookexecution",
            index=models.Index(
                fields=["organization", "-triggered_at"],
                name="incidents_s_organiz_cab8e5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="soarplaybookexecution",
            index=models.Index(
                fields=["incident", "-triggered_at"],
                name="incidents_s_inciden_57efab_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="soarplaybookexecution",
            index=models.Index(fields=["status"], name="incidents_s_status_5d6b0d_idx"),
        ),
        migrations.AddIndex(
            model_name="threatintelindicator",
            index=models.Index(
                fields=["organization", "indicator_type"],
                name="incidents_t_organiz_0ca221_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="threatintelindicator",
            index=models.Index(fields=["value"], name="incidents_t_value_8cc898_idx"),
        ),
        migrations.AddIndex(
            model_name="threatintelindicator",
            index=models.Index(
                fields=["-updated_at"], name="incidents_t_updated_557d2c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="threatintelindicator",
            unique_together={("organization", "indicator_type", "value")},
        ),
    ]
