# Generated by Django 5.2.4 on 2026-04-07 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_organization_soarplaybookexecution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AILearningHistory',
            fields=[
                ('learning_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('model-update', 'Model Update'), ('rule-tuned', 'Rule Tuned'), ('fp-correction', 'False Positive Correction'), ('pattern-learned', 'Pattern Learned'), ('threshold-adjusted', 'Threshold Adjusted')], default='pattern-learned', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('impact', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=20)),
                ('metrics_change', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_learning_history', to='incidents.organization')),
                ('related_incidents', models.ManyToManyField(blank=True, related_name='ai_learning_entries', to='incidents.incident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('critical', 'Critical'), ('escalation', 'Escalation'), ('system', 'System'), ('ai-insight', 'AI Insight')], default='system', max_length=20)),
                ('read', models.BooleanField(default=False)),
                ('dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='incidents.incident')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='incidents.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalystNote',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(default='Analyst', max_length=120)),
                ('role', models.CharField(default='SOC Analyst', max_length=120)),
                ('content', models.TextField()),
                ('note_type', models.CharField(choices=[('observation', 'Observation'), ('correction', 'Correction'), ('recommendation', 'Recommendation'), ('escalation', 'Escalation')], default='observation', max_length=20)),
                ('ai_relevant', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyst_notes', to='incidents.incident')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyst_notes', to='incidents.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ailearninghistory',
            index=models.Index(fields=['organization', '-created_at'], name='incidents_a_organiz_2c5bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='ailearninghistory',
            index=models.Index(fields=['entry_type'], name='incidents_a_entry_t_7f3d24_idx'),
        ),
        migrations.AddIndex(
            model_name='ailearninghistory',
            index=models.Index(fields=['impact'], name='incidents_a_impact_0d1e23_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization', '-created_at'], name='incidents_n_organiz_4f0b4c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['read', 'dismissed'], name='incidents_n_read_b99f18_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['category'], name='incidents_n_categor_a6fe96_idx'),
        ),
        migrations.AddIndex(
            model_name='analystnote',
            index=models.Index(fields=['incident', '-created_at'], name='incidents_a_inciden_8025dd_idx'),
        ),
        migrations.AddIndex(
            model_name='analystnote',
            index=models.Index(fields=['organization', '-created_at'], name='incidents_a_organiz_ae25f6_idx'),
        ),
        migrations.AddIndex(
            model_name='analystnote',
            index=models.Index(fields=['note_type'], name='incidents_a_note_ty_302218_idx'),
        ),
    ]
